project 'FiniteStateMachines.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FiniteStateMachines' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FiniteStateMachines
  pod 'Signals', '~> 4.0'

  target 'FiniteStateMachinesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
